const books = [
  {
    id: 1,
    title: "The Silent River",
    author: "Ava Stone",
    stock: 12,
    category: "Fiction",
  },
  {
    id: 2,
    title: "Shadows of Tomorrow",
    author: "Liam Carter",
    stock: 8,
    category: "Fiction",
  },
  {
    id: 3,
    title: "The Broken Path",
    author: "Sophia Reed",
    stock: 15,
    category: "Fiction",
  },
  {
    id: 4,
    title: "Lost in Time",
    author: "Mason Gray",
    stock: 20,
    category: "Fiction",
  },
  {
    id: 5,
    title: "Dreams of the Forgotten",
    author: "Isabella Hayes",
    stock: 11,
    category: "Fiction",
  },
  {
    id: 6,
    title: "Whispers in the Dark",
    author: "Ethan Blake",
    stock: 17,
    category: "Fiction",
  },
  {
    id: 7,
    title: "The Crimson Sky",
    author: "Olivia Brooks",
    stock: 6,
    category: "Fiction",
  },
  {
    id: 8,
    title: "Fragments of Truth",
    author: "Noah Bennett",
    stock: 14,
    category: "Fiction",
  },
  {
    id: 9,
    title: "The Last Horizon",
    author: "Mia Collins",
    stock: 9,
    category: "Fiction",
  },
  {
    id: 10,
    title: "The Painted Veil",
    author: "James Walker",
    stock: 13,
    category: "Fiction",
  },

  {
    id: 11,
    title: "Becoming Resilient",
    author: "Harper Lane",
    stock: 10,
    category: "Non-Fiction",
  },
  {
    id: 12,
    title: "The Art of Stillness",
    author: "Evelyn Torres",
    stock: 22,
    category: "Non-Fiction",
  },
  {
    id: 13,
    title: "Mind Over Matter",
    author: "Logan Mitchell",
    stock: 18,
    category: "Non-Fiction",
  },
  {
    id: 14,
    title: "Breaking Barriers",
    author: "Amelia Foster",
    stock: 12,
    category: "Non-Fiction",
  },
  {
    id: 15,
    title: "The Power of Choices",
    author: "Jackson Reed",
    stock: 9,
    category: "Non-Fiction",
  },
  {
    id: 16,
    title: "Silent Wisdom",
    author: "Ella James",
    stock: 20,
    category: "Non-Fiction",
  },
  {
    id: 17,
    title: "Steps to Clarity",
    author: "Carter Hayes",
    stock: 11,
    category: "Non-Fiction",
  },
  {
    id: 18,
    title: "The Courage Within",
    author: "Scarlett Moore",
    stock: 7,
    category: "Non-Fiction",
  },
  {
    id: 19,
    title: "Beyond the Comfort Zone",
    author: "Henry Brooks",
    stock: 13,
    category: "Non-Fiction",
  },
  {
    id: 20,
    title: "The Path of Simplicity",
    author: "Chloe Adams",
    stock: 16,
    category: "Non-Fiction",
  },

  {
    id: 21,
    title: "Exploring the Stars",
    author: "Benjamin Lee",
    stock: 14,
    category: "Science",
  },
  {
    id: 22,
    title: "The Quantum Realm",
    author: "Victoria Ross",
    stock: 9,
    category: "Science",
  },
  {
    id: 23,
    title: "Wonders of Biology",
    author: "Lucas Scott",
    stock: 18,
    category: "Science",
  },
  {
    id: 24,
    title: "The Physics of Light",
    author: "Emily Parker",
    stock: 20,
    category: "Science",
  },
  {
    id: 25,
    title: "The Hidden Universe",
    author: "Daniel Morris",
    stock: 12,
    category: "Science",
  },
  {
    id: 26,
    title: "Mathematics of Infinity",
    author: "Grace Kelly",
    stock: 8,
    category: "Science",
  },
  {
    id: 27,
    title: "Neuroscience Uncovered",
    author: "Michael Turner",
    stock: 17,
    category: "Science",
  },
  {
    id: 28,
    title: "The Code of Life",
    author: "Hannah Phillips",
    stock: 10,
    category: "Science",
  },
  {
    id: 29,
    title: "Climate Change Explained",
    author: "David Allen",
    stock: 15,
    category: "Science",
  },
  {
    id: 30,
    title: "The Evolution of Species",
    author: "Sophie Evans",
    stock: 11,
    category: "Science",
  },

  {
    id: 31,
    title: "Empire of Ashes",
    author: "Oliver Clark",
    stock: 6,
    category: "History",
  },
  {
    id: 32,
    title: "The Ancient World",
    author: "Ella Thompson",
    stock: 19,
    category: "History",
  },
  {
    id: 33,
    title: "The Rise and Fall of Rome",
    author: "William Harris",
    stock: 14,
    category: "History",
  },
  {
    id: 34,
    title: "Warriors of the East",
    author: "Charlotte Lewis",
    stock: 8,
    category: "History",
  },
  {
    id: 35,
    title: "Medieval Legends",
    author: "Jacob White",
    stock: 12,
    category: "History",
  },
  {
    id: 36,
    title: "The Age of Revolution",
    author: "Madison Young",
    stock: 9,
    category: "History",
  },
  {
    id: 37,
    title: "World War Chronicles",
    author: "Samuel King",
    stock: 11,
    category: "History",
  },
  {
    id: 38,
    title: "The Great Dynasties",
    author: "Lily Wright",
    stock: 20,
    category: "History",
  },
  {
    id: 39,
    title: "The Silk Road Journey",
    author: "Matthew Hill",
    stock: 16,
    category: "History",
  },
  {
    id: 40,
    title: "Colonial Encounters",
    author: "Zoe Martinez",
    stock: 10,
    category: "History",
  },

  {
    id: 41,
    title: "The Digital Age",
    author: "Elijah Hall",
    stock: 15,
    category: "Technology",
  },
  {
    id: 42,
    title: "Artificial Intelligence 101",
    author: "Aria Nelson",
    stock: 8,
    category: "Technology",
  },
  {
    id: 43,
    title: "Web Development Mastery",
    author: "Cameron Adams",
    stock: 19,
    category: "Technology",
  },
  {
    id: 44,
    title: "The Blockchain Revolution",
    author: "Layla Ramirez",
    stock: 13,
    category: "Technology",
  },
  {
    id: 45,
    title: "Cybersecurity Essentials",
    author: "Wyatt Rogers",
    stock: 7,
    category: "Technology",
  },
  {
    id: 46,
    title: "Programming with Python",
    author: "Nora Peterson",
    stock: 17,
    category: "Technology",
  },
  {
    id: 47,
    title: "The Future of Robotics",
    author: "Evan Jenkins",
    stock: 12,
    category: "Technology",
  },
  {
    id: 48,
    title: "Cloud Computing Demystified",
    author: "Stella Cooper",
    stock: 10,
    category: "Technology",
  },
  {
    id: 49,
    title: "Big Data Insights",
    author: "Jack Ramirez",
    stock: 14,
    category: "Technology",
  },
  {
    id: 50,
    title: "The Internet of Things",
    author: "Luna Howard",
    stock: 9,
    category: "Technology",
  },
];

module.exports = { books };
