DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS books;

CREATE TABLE genres(
id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR(100) NOT NULL
);

CREATE TABLE books(id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
title VARCHAR(100) NOT NULL,
stock INT NOT NULL DEFAULT 0,
author VARCHAR(100) NOT NULL,
genre_id INT REFERENCES genres(id) ON DELETE CASCADE
);  